### ISSUE TITLE
[Client] 홍윤기/서덕주/손준혁 TypeScript Redux 초기 세팅

### ISSUE THREAD

**Issue by altanis7** [codestates/backpacker-client#10]
## Work Description
- TypeScript Redux 초기 세팅하기

## TODO:
1. [x] Redux reducer action store 만들기 
2. [x] 만든 것들 타입 세팅 하기
3. [x] 세팅하고 Open API 이용해서 테스트 해보기
