### ISSUE TITLE
[Client] 회원 비회원 모달 만들기 썸네일 사진 추가

### ISSUE THREAD

**Issue by altanis7** [codestates/backpacker-client#134]
## Work Description
- 회원 비회원 모달 만들기 썸네일 사진 추가

## TODO:
1. [x] 회원 비회원 모달 구현
2. [x] 썸네일 사진 추가
3. [x] 네브바 , 모달 수정
