### ISSUE TITLE
[Client] SEO 로그인, 유저정보찾기 기능, 디자인수정

### ISSUE THREAD

**Issue by codono** [codestates/backpacker-client#36]
## Work Description
- 간단한 페이지 목업, 디자인
## TODO:
1. [x] 로그인 컴포넌트 디자인
2. [x] 유저정보찾기 페이지 목업 및 디자인
3. [x] 유저정보찾기 페이지 실패 메시지 출력
