### ISSUE TITLE
[Client] Content 작성 페이지 목업 구현

### ISSUE THREAD

**Issue by altanis7** [codestates/backpacker-client#43]
## Work Description
- Content 작성 페이지 목업 구현 및 기능 구현

## TODO:
1. [x] 세밀하게 컴포넌트 하기
2. [x] API 없이 기능 개발 가능하면 하기
3. [x] Wire Frame 대로 목업 구현하기
