### ISSUE TITLE
[Client] Content 작성 페이지 기능 구현

### ISSUE THREAD

**Issue by altanis7** [codestates/backpacker-client#58]
## Work Description
- Content 작성 페이지 기능 구현

## TODO:
1. [x] 리듀서 및 액션 작성하기
2. [x] 데이터 제대로 받아와지는지 확인하기
3. [x] 일정 추가 시 새로운 페이지 보여줄 방법 생각해보기
