### ISSUE TITLE
[Client] 컨텐츠 리스트 페이지 수정

### ISSUE THREAD

**Issue by codono** [codestates/backpacker-client#59]
## Work Description
- 필터링 조건을 바탕으로 서버에서 받아온 데이터를 필터하여 렌더하도록 기능 수정

## TODO:
1. [x] 서버에서 전체 데이터 불러오기
2. [x] 도시 이름, 예산 필터링 데이터 구현
3. [x] 구현 된 데이터 렌더
